CPPFLAGS=-std=c++2a -Wall -Wextra -pedantic -O3 -fPIE -fconcepts -fconstexpr-depth=33554432 -fconstexpr-ops-limit=1000000009
DEFINES64=-DSECRETVALUE=01337 -DWINLEN=3
DEFINES32=-DSECRETVALUE=0x1337 -DWINLEN=7
all:
	#g++ ${CPPFLAGS} ${DEFINES64} -s ct.cpp -o part64_2
	#g++ ${CPPFLAGS} ${DEFINES64} -g3 ct.cpp -o debug_prog64
	#g++ ${CPPFLAGS} ${DEFINES32} -s -m32 ct.cpp -o part32_3
	#g++ ${CPPFLAGS} ${DEFINES32} -g3 -m32 ct.cpp -o debug_prog32

